spring:
  application:
    name: springBoot-data-Jpa
  datasource:
    url: jdbc:postgresql://localhost:5432/java_workshopsdb
    driver-class-name: org.postgresql.Driver
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
#    user:
#    password:
    baseline-description: "int"
    baseline-version: 0




